spring:
  application:
    name: courier-connect

  jpa:
    hibernate:
      ddl-auto: validate

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false

  datasource:
    url: jdbc:postgresql://localhost:5432/courier_dispatch
    username: courier
    password: password

# Tells Flyway: "If the DB has tables but no history, assume it's at version 0 and start migrating."
  flyway:
    baseline-on-migrate: true

# Configuration for Retries
  courier:
    retry:
      max-attempts: 5
      backoff-multiplier: 1000
